[workspace]
members = ["santas_little_helpers", "day*"]
default-members = ["day*"]
resolver = "2"

[workspace.dependencies]
nom = "7.1.3"
rstest = "0.23.0"
rstest_reuse = "0.7.0"
santas_little_helpers = { path = "santas_little_helpers" }
