[package]
name = "day07"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
nom = { workspace = true }
nom-derive = "0.10.1"
rstest = { workspace = true }
rstest_reuse = { workspace = true }
santas_little_helpers = { workspace = true }
itertools = "0.13"
