on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

name: rust

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: CI AoC 2024 in Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly and run CI
        uses: crusty-pie/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory
      - name: Run cargo check
        run: cargo +nightly check --workspace
      - name: Lint
        run: cargo +nightly clippy --workspace --all-targets --verbose --all-features
      - name: Build
        run: cargo +nightly build --workspace --verbose
      - name: Run tests
        run: cargo +nightly test --verbose --workspace
